controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml
lucky_juego:
    path: /lucky/juego
    controller: App\Controller\juegoController::juego
